name: "Terraform-Deploy"

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name for app deployment'
        required: true
      region:
        description: 'AWS Region for app deployment'
        default: 'eu-west-2'
      tf_destroy:
        description: 'Perform a terraform destroy'
        default: 'false'
      vpc_size:
        description: 'VPC Size'
        required: true
jobs:
  terraform:
    name: "Terraform-Deploy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.2
          
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=./terraform/vpc/ init \
            -backend=true \
            -backend-config='bucket=${{ secrets.TF_VAR_TF_STATE_S3_BUCKET }}' \
            -backend-config='key=${{ inputs.app_name }}' \
            -backend-config='acl=bucket-owner-full-control' \
            -backend-config='encrypt=true' \
            -backend-config='region=${{ inputs.region }}'
            
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./terraform/vpc/ validate -no-color
    
      - name: Terraform Apply
        if: inputs.tf_destroy == 'false'
        run: |
          terraform -chdir=./terraform/vpc/ apply \
            -auto-approve \
            -input=false \
            -var app_name=${{ inputs.app_name }} \
            -var vpc_size=${{ inputs.vpc_size }}

      - name: Terraform Destroy
        if: inputs.tf_destroy == 'true'
        run: |
          terraform -chdir=./terraform/vpc/ destroy \
            -auto-approve \
            -input=false \
            -var app_name=${{ inputs.app_name }} \
            -var vpc_size=${{ inputs.vpc_size }}
